# Generated by Django 4.2.2 on 2023-06-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_orderitem_customer_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transation_id',
            new_name='transaction_id',
        ),
    ]
