# Generated by Django 4.2.2 on 2023-06-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_name_ticketanswer_user_alter_ticket_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='images',
        ),
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='support.ticketanswer'),
        ),
    ]
