# Generated by Django 4.2.2 on 2023-06-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_ticket_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketanswer',
            name='user',
        ),
        migrations.AddField(
            model_name='ticketanswer',
            name='admin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
